name: DETECT-VERSION

on:
  #自动：
  #schedule:
   # - cron: 0 20 * * *
  #手动
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  detect-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Kernel Version
        run: |
          KERNEL_VERSION=$(curl -sL 'https://raw.githubusercontent.com/VIKINGYFY/immortalwrt/refs/heads/main/target/linux/generic/kernel-6.18' | sed -n 's/^LINUX_VERSION-6\.18 = \(.*\)$/6.18\1/p')
          OPENCLASH_VERSION=$(curl -sL 'https://raw.githubusercontent.com/vernesong/OpenClash/refs/heads/master/luci-app-openclash/Makefile' | sed -n 's/^PKG_VERSION:=//p')
          echo "Kernel: $KERNEL_VERSION"
          echo "OpenClash: $OPENCLASH_VERSION"
          echo "KERNEL_VERSION=$KERNEL_VERSION" >> "$GITHUB_ENV"
          
      - name: Trigger OWRT-TEST
        if: ${{ env.KERNEL_VERSION == '6.18.88' || env.KERNEL_VERSION == '6.18.80' }}
        run: |
          gh workflow run OWRT-TEST.yml --repo $GITHUB_REPOSITORY
