name: DETECT-VERSION

on:
  #自动：
  #schedule:
   # - cron: 0 20 * * *
  #手动
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  detect-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone VIKINGYFY-ImmortalWrt
        run: |
          git clone --depth=1 --single-branch --branch main https://github.com/VIKINGYFY/immortalwrt.git ./wrt/

      - name: Get Kernel Version
        run: |
          cd ./wrt/
          echo "WRT_KVER=$(find ./bin/targets/ -type f -name "*.manifest" -exec grep -oP '^kernel - \K[\d\.]+' {} \;)" >> $GITHUB_ENV
          OPENCLASH_VER=$(sed -n 's/^PKG_VERSION:=//p' "https://raw.githubusercontent.com/vernesong/OpenClash/refs/heads/master/luci-app-openclash/Makefile" | head -n1)
          echo "OPENCLASH_VERSION=$OPENCLASH_VER"
          echo "WRT_KVER=$(find ./bin/targets/ -type f -name "*.manifest" -exec grep -oP '^kernel - \K[\d\.]+' {} \;)"
          
      - name: Trigger OWRT-ALL
        if: env.WRT_KVER == '6.18.88' || env.WRT_KVER == '6.18.80' 
        run: |
          gh workflow run OWRT-ALL.yml --repo $GITHUB_REPOSITORY
